In [3]:
import pandas as pd
import numpy as np

# 建立範例資料
data = {
    '姓名': ['張三', '李四', '王五', '陳六', '林七'],
    '年齡': [25, 30, 35, 40, np.nan],
    '薪資': [50000, 60000, 75000, 85000, 45000],
    '部門': ['研發', '行銷', '研發', '行銷', '研發']
}

# 建立 DataFrame
df = pd.DataFrame(data)

# 1. 查看基本資訊（資料類型、非空值數量等）
print("基本資訊：")
df.info()

# 2. 查看數值欄位的統計摘要
print("\n統計摘要：")
print(df.describe())

# 3. 查看前幾筆資料
print("\n前5筆資料：")
print(df.head())

# 4. 查看維度（列數和欄數）
print("\n資料維度:", df.shape)

# 5. 查看欄位名稱
print("\n欄位名稱:", df.columns)

# 6. 查看索引
print("\n索引:", df.index)

# 7. 查看資料型態
print("\n資料型態:\n", df.dtypes)

# 8. 查看是否有缺失值
print("\n缺失值統計:\n", df.isnull().sum())

# 9. 查看重複資料
print("\n重複資料數:", df.duplicated().sum())

基本資訊：
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      5 non-null      object
 1   年齡      4 non-null      float64
 2   薪資      5 non-null      int64
 3   部門      5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

統計摘要：
              年齡            薪資
count   4.000000      5.000000
mean   32.500000  63000.000000
std     6.454972  16807.736314
min    25.000000  45000.000000
25%    28.750000  50000.000000
50%    32.500000  60000.000000
75%    36.250000  75000.000000
max    40.000000  85000.000000

前5筆資料：
   姓名    年齡     薪資  部門
0  張三  25.0  50000  研發
1  李四  30.0  60000  行銷
2  王五  35.0  75000  研發
3  陳六  40.0  85000  行銷
4  林七   NaN  45000  研發

資料維度: (5, 4)

欄位名稱: Index(['姓名', '年齡', '薪資', '部門'], dtype='object')

索引: RangeIndex(start=0, stop=5, step=1)

資料型態:
 姓名     object
年齡    float64
薪資      int64
部門     object
dtype: object

缺失值統計:
 姓名    0
年齡    1
薪資    0
部門    0
dtype: int64

重複資料數: 0

In [9]:
import pandas as pd
import numpy as np

# 建立一個包含 NaN 值的 DataFrame
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 7, 8, 9, 10],
    'C': [11, 12, 13, 14, np.nan],
    'D': [15, 16, 17, 18, 19],
    'E': [20,21,22,23,24]
}
df = pd.DataFrame(data)

print("原始 DataFrame：")
print(df)

# 刪除任何包含 NaN 值的列
df_dropped = df.dropna(axis=1)

print("\n刪除包含 NaN 值的列後的 DataFrame：")
print(df_dropped)

# 說明
# df.dropna(axis=1) 的作用是：
#   - dropna()：用於刪除 DataFrame 中包含 NaN 值的行或列。
#   - axis=1：指定刪除列（axis=0 則表示刪除行）。
#   - 預設情況下，dropna() 會刪除任何包含至少一個 NaN 值的行或列。
import pandas as pd
import numpy as np

# 建立一個包含 NaN 值的 DataFrame
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 7, 8, 9, 10],
    'C': [11, 12, 13, 14, np.nan],
    'D': [15, 16, 17, 18, 19],
    'E': [20,21,22,23,24]
}
df = pd.DataFrame(data)

print("原始 DataFrame：")
print(df)

# 刪除任何包含 NaN 值的行
df_dropped = df.dropna(axis=0)  # 或者簡寫為 df.dropna()
import pandas as pd
import numpy as np

# 1. Define subjects and student names
subjects = ['國文', '英文', '數學', '自然', '社會']
student_names = ['小明', '小華', '小美', '小強', '小玉']

# 2. Create a DataFrame with random scores (50-100)
np.random.seed(0)  # for reproducibility
scores = np.random.randint(50, 101, size=(len(student_names), len(subjects)))
df = pd.DataFrame(scores, columns=subjects, index=student_names)

# 3. Style function to highlight scores below 60 in red
def highlight_low_scores(val):
    """
    Highlights scores below 60 in red.
    """
    color = 'red' if val < 60 else 'whiteimport pandas as pd
    import numpy as np
    
    # Define subjects and student names (from previous context, but still relevant)
    subjects = ['國文', '英文', '數學', '自然', '社會']
    student_names = ['小明', '小華', '小美', '小強', '小玉']
    
    # Create a DataFrame with random scores (50-100) (from previous context, but still relevant)
    np.random.seed(0)  # for reproducibility
    scores = np.random.randint(50, 101, size=(len(student_names), len(subjects)))
    df = pd.DataFrame(scores, columns=subjects, index=student_names)
    
    # 1. Add a "總分" (Total Score) column
    df['總分'] = df.sum(axis=1)  # Sum across rows (axis=1)
    
    # 2. Sort the DataFrame by "總分" in descending order
    df_sorted = df.sort_values(by='總分', ascending=False)
    
    # 3. add the ranking depend on "總分"
    df_sorted['名次'] = df_sorted['總分'].rank(ascending=False, method='min').astype(int)
    
    # 4. Display the sorted DataFrame with "總分"
    print("依總分排序後的成績表：")
    print(df_sorted)
    import pandas as pd
    import numpy as np
    
    # Define subjects and student names (from previous context, but still relevant)
    subjects = ['國文', '英文', '數學', '自然', '社會']
    student_names = ['小明', '小華', '小美', '小強', '小玉']
    
    # Create a DataFrame with random scores (50-100) (from previous context, but still relevant)
    np.random.seed(0)  # for reproducibility
    scores = np.random.randint(50, 101, size=(len(student_names), len(subjects)))
    df = pd.DataFrame(scores, columns=subjects, index=student_names)
    
    # 1. Add a "總分" (Total Score) column
    df['總分'] = df.sum(axis=1)  # Sum across rows (axis=1)
    
    # 2. Sort the DataFrame by "總分" in descending order
    df_sorted = df.sort_values(by='總分', ascending=False)
    
    # 3. add the ranking depend on "總分"
    df_sorted['名次'] = df_sorted['總分'].rank(ascending=False, method='min').astype(int)
    
    # 4. Display the sorted DataFrame with "總分"
    print("依總分排序後的成績表：")
    print(df_sorted)
    '
    return f'color: {color}'

# 4. Apply styling to the DataFrame
styled_df = df.style.applymap(highlight_low_scores)

# 5. Display the styled DataFrame
print("成績表 (低於 60 分標示為紅色)：")
display(styled_df)

# 6.Print normal DataFrame
print("\n成績表 (原始DataFrame)：")
print(df)

print("\n刪除包含 NaN 值的行後的 DataFrame：")
print(df_dropped)

SyntaxError: unterminated string literal (detected at line 63) (3900407453.py, line 63)

In [10]:
import pandas as pd
import numpy as np

# Define subjects and student names (from previous context, but still relevant)
subjects = ['國文', '英文', '數學', '自然', '社會']
student_names = ['小明', '小華', '小美', '小強', '小玉']

# Create a DataFrame with random scores (50-100) (from previous context, but still relevant)
np.random.seed(0)  # for reproducibility
scores = np.random.randint(50, 101, size=(len(student_names), len(subjects)))
df = pd.DataFrame(scores, columns=subjects, index=student_names)

# 1. Add a "總分" (Total Score) column
df['總分'] = df.sum(axis=1)  # Sum across rows (axis=1)

# 2. Sort the DataFrame by "總分" in descending order
df_sorted = df.sort_values(by='總分', ascending=False)

# 3. add the ranking depend on "總分"
df_sorted['名次'] = df_sorted['總分'].rank(ascending=False, method='min').astype(int)

# 4. Display the sorted DataFrame with "總分"
print("依總分排序後的成績表：")
print(df_sorted)

依總分排序後的成績表：
    國文  英文  數學  自然   社會   總分  名次
小玉  96  74  67  87   75  399   1
小華  89  59  69  71  100  388   2
小美  86  73  56  74   74  363   3
小強  62  51  88  89   73  363   3
小明  94  97  50  53   53  347   5

In [12]:
import pandas as pd
import numpy as np

# 1. Create a Sample DataFrame (No previous context assumed)
np.random.seed(0)
subjects = ['國文', '英文', '數學', '自然', '社會']
student_names = ['小明', '小華', '小美', '小強', '小玉']
scores = np.random.randint(50, 101, size=(len(student_names), len(subjects)))
df = pd.DataFrame(scores, columns=subjects, index=student_names)

# 2. Add a "總分" column
df['總分'] = df.sum(axis=1)

# 3. Sort by "總分" and add the "名次" column
df_sorted = df.sort_values(by='總分', ascending=False)
df_sorted['名次'] = df_sorted['總分'].rank(ascending=False, method='min').astype(int)

# 4. Move "名次" to the front
cols = ['名次'] + [col for col in df_sorted.columns if col != '名次']
df_reordered = df_sorted[cols]

# 5. Style the DataFrame (highlight low scores in red)
def highlight_low_scores(val):
    """Highlights scores below 60 in red."""
    color = 'red' if isinstance(val, (int, float)) and val < 60 else 'white'
    return f'color: {color}'

styled_df = df_reordered.style.applymap(highlight_low_scores)

# 6. Display the Styled DataFrame
print("最終成績表 (已對齊，低於 60 分標示為紅色，名次在最前面)：")
display(styled_df)

最終成績表 (已對齊，低於 60 分標示為紅色，名次在最前面)：

C:\Users\bigpa\AppData\Local\Temp\ipykernel_24952\555725367.py:28: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df_reordered.style.applymap(highlight_low_scores)